# Generated by Django 2.1.1 on 2018-09-24 11:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='complete',
            new_name='mark',
        ),
        migrations.AddField(
            model_name='todo',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 24, 11, 8, 16, 835417, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='dueon',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 24, 11, 8, 33, 792406, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='owner',
            field=models.ForeignKey(default=datetime.datetime(2018, 9, 24, 11, 10, 59, 320653, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='main.Human'),
            preserve_default=False,
        ),
    ]
