# Generated by Django 2.1.3 on 2018-11-05 09:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181105_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 5, 9, 38, 25, 93396, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='dueon',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 7, 9, 38, 25, 93426, tzinfo=utc)),
        ),
    ]
