# Generated by Django 2.1.3 on 2018-11-04 17:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181104_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 4, 17, 19, 27, 546694, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='dueon',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 6, 17, 19, 27, 546724, tzinfo=utc)),
        ),
    ]
