# Generated by Django 2.1.3 on 2018-11-06 08:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20181105_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 6, 8, 36, 49, 283292, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='dueon',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 8, 8, 36, 49, 283322, tzinfo=utc)),
        ),
    ]
