# Generated by Django 2.1.3 on 2018-11-05 09:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20181104_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 5, 9, 36, 15, 840648, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='dueon',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 7, 9, 36, 15, 840677, tzinfo=utc)),
        ),
    ]
